config/routes.rb
SagerApp::Application.routes.draw do

  resources :schedules

  devise_for :users

  match 'sensors/get_current_month_kwh_usage' => 'sensors#get_current_month_kwh_usage'
  resources :sensors

  resources :sensor_readings, :only => [:index, :show, :create]

  root :to => "pages#start"

  get "pages/home"
  get "pages/about"
  get "pages/trends"
  get "pages/start"
  get "pages/budgets"
  get "pages/dashboard"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :end_time, :sensor_id, :start_time

  #
  # Validations
  #
  validates_presence_of :sensor_id
  validates_presence_of :start_time
  validates_presence_of :end_time

  #
  # Associations
  #
  belongs_to :sensor
end

app/controllers/schedules_controller.rb
 class SchedulesController < ApplicationController
  #
  # Devise
  #
  before_filter :authenticate_user!

  #
  # CanCan
  #
  load_and_authorize_resource

  # GET /schedules
  # GET /schedules.json
  def index
    if params[:sensor_id].present?
       #sensors_found = Sensor.where(:mac_address => params[:mac_address])
       @schedules = Schedule.find(:all, :conditions => {:sensor_id => params[:sensor_id]})
    else
       @schedules = Schedule.accessible_by(current_ability)
    end

    #@schedules = Schedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:schedules => @schedules} }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.number_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.number_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :sensor_id %><br />
    <%= f.number_field :sensor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <tr>
    <th>Start time</th>
    <th>End time</th>
    <th>Sensor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.start_time %></td>
    <td><%= schedule.end_time %></td>
    <td><%= schedule.sensor_id %></td>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Destroy', schedule, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start time:</b>
  <%= @schedule.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @schedule.end_time %>
</p>

<p>
  <b>Sensor:</b>
  <%= @schedule.sensor_id %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>