config/routes.rb
SagerApp::Application.routes.draw do

  resources :schedules

  devise_for :users

  match 'sensors/get_current_month_kwh_usage' => 'sensors#get_current_month_kwh_usage'
  resources :sensors

  resources :sensor_readings, :only => [:index, :show, :create]

  root :to => "pages#start"

  get "pages/home"
  get "pages/about"
  get "pages/trends"
  get "pages/start"
  get "pages/budgets"
  get "pages/dashboard"

end

app/models/sensor_reading.rb
class SensorReading < ActiveRecord::Base
  attr_accessible :sensor_id, :watthours, :created_at
  #
  # Associations
  #
  belongs_to :sensor
  validates_presence_of :sensor
end

app/controllers/sensor_readings_controller.rb
class SensorReadingsController < ApplicationController
  #
  # Devise
  #
  before_filter :authenticate_user!, :except => [:create]

  #
  # CanCan
  #
  load_and_authorize_resource :except => [:create]

  # GET /sensor_readings
  # GET /sensor_readings.json
  def index
    @sensor_readings = SensorReading.accessible_by(current_ability)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sensor_readings }
    end
  end

  # GET /sensor_readings/1
  # GET /sensor_readings/1.json
  def show
    @sensor_reading = SensorReading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sensor_reading }
    end
  end

  # POST /sensor_readings
  # POST /sensor_readings.json
  def create
    # This whole logic feels poorly eloquent, I'll research a more succint approach
    @sensor_reading = SensorReading.new

    # input validation
    unless(params[:sensor_reading][:mac_address].nil? ||
           params[:sensor_reading][:watthours].nil?)
      logger.debug 'input valid!'
      logger.debug "Params hash: #{params.inspect}"

      # given the mac address, we can find the sensor
      sensor = Sensor.find_by_mac_address(params[:sensor_reading][:mac_address])
      logger.debug "hub attributes: #{sensor.attributes.inspect}"

      # we then store the reading for that specific sensor
      @sensor_reading = SensorReading.new(:sensor_id => sensor.id,
                                          :watthours => params[:sensor_reading][:watthours])
      logger.debug "sensor_reading attributes: #{@sensor_reading.attributes.inspect}"
    end

    logger.debug 'past input valid'

    respond_to do |format|
      if @sensor_reading.save
        logger.debug "@sensor_reading saved succesfully"
        format.html { redirect_to @sensor_reading, notice: 'Sensor reading was successfully created.' }
        format.json { render json: @sensor_reading, status: :created, location: @sensor_reading }
      else
        logger.debug "@sensor_reading save failed"
        format.html { render action: "new" }
        format.json { render json: @sensor_reading.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/sensor_readings/_form.html.erb
<%= form_for(@sensor_reading) do |f| %>
  <% if @sensor_reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor_reading.errors.count, "error") %> prohibited this sensor_reading from being saved:</h2>

      <ul>
      <% @sensor_reading.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :watthours %><br />
    <%= f.number_field :watthours %>
  </div>
  <div class="field">
    <%= f.label :sensor_id %><br />
    <%= f.number_field :sensor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensor_readings/edit.html.erb
<h1>Editing sensor_reading</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor_reading %> |
<%= link_to 'Back', sensor_readings_path %>

app/views/sensor_readings/index.html.erb
<h1>Sensor readings for <%= current_user.email %></h1>

<table>
  <tr>
    <th>Watt-hours</th>
    <th>Sensor #</th>
    <th>Timestamp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sensor_readings.each do |sensor_reading| %>
  <tr>
    <td><%= sensor_reading.watthours %></td>
    <td><%= sensor_reading.sensor_id %></td>
    <td><%= sensor_reading.created_at.in_time_zone('Pacific Time (US & Canada)').to_s(:long_ordinal) %></td>
    <%# <td><%= link_to 'Show', sensor_reading %1></td> %>
    <%# <td><%= link_to 'Edit', edit_sensor_reading_path(sensor_reading) %1></td> %>
    <%# <td><%= link_to 'Destroy', sensor_reading, confirm: 'Are you sure?', method: :delete %1></td> %>
  </tr>
<% end %>
</table>

<br />

<%# <%= link_to 'New Sensor reading', new_sensor_reading_path %1> %>

app/views/sensor_readings/new.html.erb
<h1>New sensor_reading</h1>

<%= render 'form' %>

<%= link_to 'Back', sensor_readings_path %>

app/views/sensor_readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Watthours:</b>
  <%= @sensor_reading.watthours %>
</p>

<p>
  <b>Sensor:</b>
  <%= @sensor_reading.sensor_local_id %>
</p>


<%# <%= link_to 'Edit', edit_sensor_reading_path(@sensor_reading) %1> | %>
<%= link_to 'Back', sensor_readings_path %>