config/routes.rb
SagerApp::Application.routes.draw do

  resources :schedules

  devise_for :users

  match 'sensors/get_current_month_kwh_usage' => 'sensors#get_current_month_kwh_usage'
  resources :sensors

  resources :sensor_readings, :only => [:index, :show, :create]

  root :to => "pages#start"

  get "pages/home"
  get "pages/about"
  get "pages/trends"
  get "pages/start"
  get "pages/budgets"
  get "pages/dashboard"

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessor :is_scheduled_to_be_off, :current_month_kwh_usage_by_day
  attr_accessible :user_id, :mac_address, :label, :enabled, :plus

  #
  # Validations
  #
  validates_presence_of :mac_address
  validates_uniqueness_of :mac_address
  validates_presence_of :user

  #
  # Associations
  #
  belongs_to :user
  has_many :sensor_readings
  has_many :schedules


  # The following section needs to move to a controller or helper method
  # -----------------------------------------------------------
  # Add virtual attributes to JSON hash
  #def as_json(options = { })
  #  super((options || { }).merge({
  #      :methods => [:current_month_kwh_usage_by_day]
  #  }))
  #end

  # Get the total kwh usage for the current hour
  def current_hour_kwh_usage
    total_hour_kwh_usage_on(Time.now.utc.to_date, Time.now.utc.hour).round(2)
  end

  # Get the total kwh usage for the current day
  def current_day_kwh_usage
    total_day_kwh_usage_on(Time.now.utc.to_date).round(2)
  end

  # Get the total kwh usage for the current week
  def current_week_kwh_usage
    total_week_kwh_usage_until(Time.now.utc.to_date).round(2)
  end

  # Get the kwh usage for each day for the last 7 days
  def last_7_day_kwh_usage_by_day
     usage_data = []
      Time.now.utc.to_date.downto(6.days.ago.utc.to_date).each do |date|
        usage_data << total_day_kwh_usage_on(date).round(2)
      end
      usage_data
  end

  # Get the kwh usage for each day for the current week
  def current_month_kwh_usage_by_day
    current_date = Time.now.utc.to_date
    num_days_until_yesterday = current_date.day - 1
    usage_data = []
      current_date.downto(num_days_until_yesterday.days.ago.utc.to_date).each do |date|
        usage_data << total_day_kwh_usage_on(date).round(2)
      end
      usage_data
  end

  # -----------------------------------------------------------

  # Calculate the total kwh usage for a given date (UTC) and hour (range = 0..23)
  def total_hour_kwh_usage_on(date, hour)
    raise "Invalid argument: Please use a non negative value for hour" if hour < 0
    raise "Invalid argument: Please use a value that is less than or equal to 23 for hour" if hour > 23

    lower = date + hour.hour
    upper = lower + 1.hour

    return 0.0 unless lower < Time.now.utc

    connection = ActiveRecord::Base.connection()
    pgresult = connection.execute(
      "SELECT SUM(watthours)
        FROM sensor_readings
        WHERE sensor_id = #{id}
        AND created_at BETWEEN '#{lower}' and '#{upper}'")
    output = pgresult.nil? ? 0.0 : (pgresult[0].values[0].to_f)/60/1000
end

  # Calculate the total kwh usage for a given date (UTC)
  def total_day_kwh_usage_on(date)
    raise "Invalid argument: Please use a date value that is not in the future" if (date > Time.now.utc.to_date)

    cumulative_hourly_kwh_usage = 0.0
    (0..23).each do |i|
      cumulative_hourly_kwh_usage += self.total_hour_kwh_usage_on(date, i)
      #puts cumulative_hourly_kwh_usage.to_s
    end
    cumulative_hourly_kwh_usage
  end

  # Calculate the total kwh usage for the week until the specified date (UTC)
  def total_week_kwh_usage_until(date)
    raise "Invalid argument: Please use a date value that is not in the future" if (date > Time.now.utc.to_date)

    cumulative_daily_kwh_usage = 0.0
    (0..date.wday).each do |i|
      cumulative_daily_kwh_usage += self.total_day_kwh_usage_on(date - i.day)
    end
    cumulative_daily_kwh_usage
  end

  # Calculate the total kwh usage for the month until the specified date (UTC)
  def total_month_kwh_usage_until(date)
    raise "Invalid argument: Please use a date value that is not in the future" if (date > Time.now.utc.to_date)

    cumulative_daily_kwh_usage = 0.0
    (1..date.day).each do |i|
      cumulative_daily_kwh_usage += self.total_day_kwh_usage_on(date - i.day)
    end
    cumulative_daily_kwh_usage
  end

  # Is the sensor scheduled to be off?
  def is_scheduled_to_be_off
    offset_to_pdt = -25200
    current_time = Time.now.utc + offset_to_pdt
    current_time_minutes = (current_time.hour * 60) + current_time.min
    self.schedules.each do |schedule|
      return true if (current_time_minutes > schedule.start_time) && (current_time_minutes < schedule.end_time)
    end
    false
  end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController

  #
  # Devise
  #
  before_filter :authenticate_user!, :except => [:index, :update]

  #
  # CanCan
  #
  load_and_authorize_resource
  skip_authorize_resource :only => [:index, :update]

  # GET /sensors
  # GET /sensors.json
  def index
    # I don't envision passing the mac address at this point, instead some kind
    # of unique user identifier. This is a workaround for now.
    @sensors = Sensor.all

    @sensors.each do |sensor|
      sensor.enabled = 0 if sensor.is_scheduled_to_be_off
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:sensors => @sensors} }
    end
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @sensor = Sensor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/new
  # GET /sensors/new.json
  def new
    @sensor = Sensor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/1/edit
  def edit
    @sensor = Sensor.find(params[:id])
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(params[:sensor])
    @sensor.user_id = current_user.id
    @sensor.enabled = true

    # the form will pass the last 6 alphanumerics by default since the first 10
    # are always identical and do not need to be specified by the user
    if(!@sensor.mac_address.nil?)
      @sensor.mac_address = "000D6F0000" + @sensor.mac_address
    end

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to root_path, notice: 'Sensor was successfully created.' }
        format.json { render json: @sensor, status: :created, location: @sensor }
      else
        format.html { render action: "new" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sensors/1
  # PUT /sensors/1.json
  def update
    @sensor = Sensor.find(params[:id])

    respond_to do |format|
      if @sensor.update_attributes(params[:sensor])
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy

    respond_to do |format|
      format.html { redirect_to sensors_url }
      format.json { head :no_content }
    end
  end

  # GETs the kWh usage for each day of the current month
  def get_current_month_kwh_usage
    sensor = Sensor.find(params[:sensor_id])
    current_month_kwh_usage_by_day = nil
    current_month_kwh_usage_by_day = sensor.current_month_kwh_usage_by_day unless sensor.nil?
    current_month_kwh_usage = 0

    unless current_month_kwh_usage_by_day.nil?
      current_month_kwh_usage_by_day.each do |usage|
         current_month_kwh_usage = current_month_kwh_usage + usage
      end
    end

    respond_to do |format|
      format.json { render json: {:current_month_kwh_usage => current_month_kwh_usage } }
    end
  end
end

app/views/sensors/_form.html.erb
<div class="row">
  <div class="span4">
    <%= form_for(@sensor) do |f| %>
      <% if @sensor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

          <ul>
          <% @sensor.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :label, "Circle ID"%>
        <%= f.text_field :label %>
      </div>
      <div class="field input-prepend">
        <%= f.label :mac_address %>
        <span class="add-on">000D6F0000</span><%= f.text_field :mac_address, :maxlength => 6, :size => 6 %>
      </div>
      <div class="field">
        <%= f.label :plus, "Is it a Plus Circle?" %>
        <%= f.check_box :plus%>
      </div>
       <br />
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
  <div id="span4">
    <%= image_tag("circle_back_label.JPG", :width => "350") %>
  </div>
</div>

app/views/sensors/edit.html.erb
<h5>Editing sensor</h5>
<br />

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Label</th>
    <th>MAC address</th>
    <th>Enabled</th>
    <th>Circle +</th>
    <th>Scheduled off</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.label %></td>
        <td><%= sensor.mac_address %></td>
        <td><%= sensor.enabled %></td>
        <td><%= sensor.plus %></td>
        <td><%= sensor.is_scheduled_to_be_off %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/sensors/new.html.erb
<div class="row">
  <div class="span2"></div>
  <div class="span8 offset2 well">
    <h5>Add New Sensor</h5>
    <br />

    <%= render 'form' %>

    <%= link_to 'Back', sensors_path %>
  </div>
  <div class="span2"></div>
</div>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @sensor.label %>
</p>

<p>
  <b>Mac Address:</b>
  <%= @sensor.mac_address %>
</p>

<p>
  <b>Enabled:</b>
  <%= @sensor.enabled %>
</p>

<p>
  <b>Plus:</b>
  <%= @sensor.plus %>
</p>

<p>
  <b>Scheduled off:</b>
  <%= @sensor.is_scheduled_to_be_off %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>